### ISSUE TITLE
Revert merges and make tests green

### ISSUE THREAD

**Issue by robfrawley** [avalanche123/Imagine#529]
@avalanche123 @burzum We really need to get a handle on these tests, and also ensure anything new merged has a comprehensive test to go with it. We should revert the merges that were performed a few days ago to a commit that had green tests, fixing any tests that are failing, and then walk through those merges again (where appropriate) while ensuring the following

- The merged code actually implements relevant tests
- They pass all tests
- They don't introduce regressions and/or deprecations
- They provide documentation

**Comment by burzum** [comment]
@robfrawley I agree with you in all points, but who's going to do all of this work? I would do it if you tell me a way to extend my personal time bubble to have 48+h a day instead of just 24. I'm already engaged with CakePHP and my personal plugins / projects.

**Comment by robfrawley** [comment]
I'll give it a go tomorrow. :+1:

**Comment by romainneutron** [comment]
Fixed by #530

**Comment by robfrawley** [comment]
@romainneutron This isn't fixed; we haven't reverted anything yet.

**Comment by robfrawley** [comment]
Open PRs from @romainneutron to revert merges: #538, #537, #536, #535, #534, #533, #532.

**Comment by robfrawley** [comment]
All revert PRs merged.
