### ISSUE TITLE
Faster Packagist refreshing

### ISSUE THREAD

**Issue by MacDada** [avalanche123/Imagine#563]
Hi,

in `composer.json` I have `"imagine/imagine": "~0.7.0"`. It downloads `v.0.7.0` as it is the newest version currently available at Packagist: https://packagist.org/packages/imagine/imagine

About 6 hours ago [you released `v0.7.1`](https://github.com/avalanche123/Imagine/releases/tag/v0.7.1). Packagist probably needs some refreshing to get that.

I guess you could make the process faster with Github hooks: https://packagist.org/about#how-to-update-packages

~~For now, I have to downgrade to `v0.6.3` as `v0.7.0` is failing my PHPUnit tests…~~ `v0.7.1` is already on Packagist :)

**Comment by craue** [comment]
Tag v0.7.1 had to be pushed manually to packagist. So @romainneutron, please check that the update hook for this repo is set up properly.

**Comment by robfrawley** [comment]
@avalanche123 Would be the one with access to the setting page of this repository.

**Comment by romainneutron** [comment]
It seems it has been fixed 
![image](https://cloud.githubusercontent.com/assets/137574/26309656/1752b0a6-3efe-11e7-91b3-01c04ae2e800.png)

**Comment by MacDada** [comment]
@romainneutron `v0.7.1` is available on Packagist for a long time now.

But the problem remains – as a new version would have a lag too. Unless you set up hooks to update Packagist when new version arrives.

**Comment by craue** [comment]
@romainneutron, v0.7.1 is only available because @Seldaek manually triggered an update after its release.
